### PR TITLE
Switch to gradle based build and add AssetReader

### PR DESCRIPTION
**Pull request by MaVo159**
I switched the simple example to the new build system. I also moved the example into a new examples folder (examples/minimal), to keep the examples separated from the library, while allowing us to reuse the build-script (examples/build-android.sh). The root directory is already a bit cluttered anyway and I want to add at least one more example (test app for asset code).

Some of the documentation is a bit rough around the edges, but overall this build process is a lot smoother and requires fewer prerequisites. You don't even need to install the sdk anymore, since gradle and the sdk command line tools install everything you need automatically.

The other examples should be trivial to convert, but I don't have time for that right now. Asset code updates and test app will follow shortly.

This PR is mostly for comments for now. Let me know if you want me to change anything, that makes my life a bit easier than merging back and forth between repos, since I'll be working on the example folder. I'll update the PR with more asset stuff and an example for testing soon.

### CODE REVIEW

**Comment by MaVo159** [comment]
Found the first bug... ....do `export ANDROID_API=26` for now, since I'm using 25 in the build script, which is apparently not a valid ndk platform.

**Comment by xlab** [comment]
Looks great, although I'd change the style of script invocation — too many `export`s for my taste :)

**Comment by MaVo159** [comment]
If I recall correctly the exports are needed to make sure the variables propagate to subshells correctly. I'll check.

I just added the AssetReader and a test app. The `testAssetsShared` fails sometimes... It looks like a deadlock, but I can't figure out what is wrong right now. Maybe the logic is fine, but Asset is really not suitable for use on different threads. I'll give it another go soon.

If Asset really isn't suitable for use on different threads we'll have to lock a goroutine to a thread and communicate via channels I guess. Well, I hope I made a mistake somewhere.

**Comment by MaVo159** [comment]
It seems that the tests work fine if I cut down on the amount of log lines being generated. Maybe Android is trying to do be smart here. I don't think there's anything wrong with the tests. Reading the same asset from different threads seems to work fine.

Regarding the script invocation style. What exactly do you mean? Would you rather have command line options instead of setting an environment variable. Or would you like to avoid the exports in the scripts?
Other than this issue, I think this patch set is good to go. Let me know if you have further comments, otherwise I'll squash the commits into 2 or 3 reasonable pieces and update the pull request.

**Comment by xlab** [comment]
Thanks for your work. 

> Would you rather have command line options instead of setting an environment variable.
Yeah, previous invocation style is preferred (see below) as it allows to copy-paste this one line from the console output and run it again, in a single action. Otherwise you'll need to copy paste all 10 lines and run in a separate shell which is not convenient.

```
mkdir -p android/jni/lib
  CC="$(ANDROID_TOOLCHAIN_DIR)/bin/arm-linux-androideabi-gcc" \
  CXX="$(ANDROID_TOOLCHAIN_DIR)/bin/arm-linux-androideabi-g++" \
  CGO_CFLAGS="-march=armv7-a" \
  GOOS=android \
  GOARCH=arm \
  GOARM=7 \
  CGO_ENABLED=1 \
  go build -buildmode=c-shared -o android/jni/lib/libexample.so
```

>  Let me know if you have further comments

I would transpile `build-android.sh` into a Makefile though.

**Comment by MaVo159** [comment]
Ah now I get it. Yes that's better.

Regarding the makefile: I don't think there's much to gain from that, so I'll leave that to you. The sdkmanager, go build -i and gradle are all smart enough to skip most of the work on repeated invocations. 
A couple of command line flags for the script may be nice though (for example in case you want to skip sdkmanager because you don't have an internet connection).

I'll fix the go build invocation and clean up the commits. Expect a proper PR later today (if I can find a connection, since I'm on trains&planes for most of today).

**Comment by xlab** [comment]
> A couple of command line flags for the script 

Yeah it's again a matter of taste, not optimisation.
I prefer Makefile actions instead of command line flags for the script, but yeah, I will try to figure that out myself.

**Comment by MaVo159** [comment]
Looks good to me now. Please merge if there are no more issues.

**Comment by xlab** [comment]
@MaVo159 please revise the opened issues.

**Comment by xlab** [comment]
Thanks again for your work, I will handle the rest of examples by myself.
I should make a section in README to acknowledge your contributions 👍

**Comment by MaVo159** [comment]
No problem. Thanks for making these packages, the least I can do is upstream my derivative pieces.

**Pull request merged**
